spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql-tabplus-tabplus-database.b.aivencloud.com:17180/tabplus?createDatabaseIfNotExist=true
        username: avnadmin
        password: AVNS_9-2DZlj1dJELHUkdDM_
    flyway:
        baseline-on-migrate: true
        baseline-version: 0
    jpa:
        show-sql: true
        
