spring:
    datasource:
        driver-class-name: com.mysql.cj.jbdc.Driver
        url: jbdc:mysql//localhost:3306/tabplusBackend?createDatabaseIfNotExist=true
        username: root
        password:   admin

    jpa:
        show-sql: true
        